<?php

// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

declare(strict_types=1);

namespace Skautik\Sdk\Resource;

use Skautik\Sdk\Api\ExportsApi;

/**
 * Bulk extracts for volumes that would be unreasonable to page through. An export is asynchronous: you request one, we build it, and you fetch the file when it is ready.
 */
final class ExportsResource
{
    public function __construct(private readonly ExportsApi $api)
    {
    }

    /**
     * List exports
     *
     * Requires the `exports:create` scope.
     */
    public function list(): mixed
    {
        return $this->api->listExports();
    }

    /**
     * Request an export
     *
     * Requires the `exports:create` scope.
     */
    public function create($export_input): mixed
    {
        return $this->api->createExport($export_input);
    }

    /**
     * Retrieve an export
     *
     * Requires the `exports:create` scope.
     */
    public function get($export_id): mixed
    {
        return $this->api->getExport($export_id);
    }
}
