<?php

// Code generated by skautikhq/skautik-sdk. DO NOT EDIT.

declare(strict_types=1);

namespace Skautik\Sdk\Resource;

use Skautik\Sdk\Api\PropertiesApi;

/**
 * The catalogue, and your own inventory within it. Read endpoints span everything we hold; write endpoints only ever touch records your organisation published.
 */
final class PropertiesResource
{
    public function __construct(private readonly PropertiesApi $api)
    {
    }

    /**
     * List properties
     *
     * Requires the `properties:read` scope.
     *
     * @param array<string, mixed> $options Any of: city, district, postal_code, type, transaction_type, status, external_id, min_price, max_price, min_living_area, min_bedrooms, limit, cursor, sort, expand.
     */
    public function list(array $options = []): mixed
    {
        return $this->api->listProperties(...$options);
    }

    /**
     * Every record, following the cursor.
     *
     * The same request as `list`, with the paging done for you.
     * It stops when the API says there are no more, which is the only correct
     * test: a full page can still be the last one, and a short page can still
     * carry a cursor. Yields records, so nothing is held beyond the page being
     * read.
     *
     * @return \Generator
     */
    public function listAll(array $options = []): \Generator
    {
        $cursor = null;

        while (true) {
            $page = $this->list(array_merge($options, $cursor === null ? [] : ['cursor' => $cursor]));

            foreach ($page->getData() as $record) {
                yield $record;
            }

            $meta = $page->getMeta();
            if ($meta === null || $meta->getHasMore() !== true) {
                return;
            }

            $following = $meta->getNextCursor();
            // A cursor that does not move would page for ever over one page,
            // which is a server fault and should not become a loop that never
            // ends.
            if ($following === null || $following === $cursor) {
                return;
            }
            $cursor = $following;
        }
    }

    /**
     * Create a property
     *
     * Requires the `properties:write` scope.
     *
     * @param array<string, mixed> $options Any of: idempotency_key.
     */
    public function create($property_input, array $options = []): mixed
    {
        return $this->api->createProperty($property_input, ...$options);
    }

    /**
     * Withdraw a property
     *
     * Requires the `properties:write` scope.
     */
    public function delete($property_id): mixed
    {
        return $this->api->deleteProperty($property_id);
    }

    /**
     * Retrieve a property
     *
     * Requires the `properties:read` scope.
     *
     * @param array<string, mixed> $options Any of: expand.
     */
    public function get($property_id, array $options = []): mixed
    {
        return $this->api->getProperty($property_id, ...$options);
    }

    /**
     * Update a property
     *
     * Requires the `properties:write` scope.
     *
     * @param array<string, mixed> $options Any of: if_match.
     */
    public function update($property_id, $property_input, array $options = []): mixed
    {
        return $this->api->updateProperty($property_id, $property_input, ...$options);
    }

    /**
     * List images
     *
     * Requires the `properties:read` scope.
     */
    public function listImages($property_id): mixed
    {
        return $this->api->listPropertyImages($property_id);
    }

    /**
     * Upload an image
     *
     * Requires the `images:write` scope.
     *
     * @param array<string, mixed> $options Any of: room_type, primary, position.
     */
    public function uploadImage($property_id, $file, array $options = []): mixed
    {
        return $this->api->uploadPropertyImage($property_id, $file, ...$options);
    }

    /**
     * Delete an image
     *
     * Requires the `images:write` scope.
     */
    public function deleteImage($property_id, $image_id): mixed
    {
        return $this->api->deletePropertyImage($property_id, $image_id);
    }

    /**
     * Price history
     *
     * Requires the `properties:read` scope.
     */
    public function priceHistory($property_id): mixed
    {
        return $this->api->propertyPriceHistory($property_id);
    }

    /**
     * Similar properties
     *
     * Requires the `properties:read` scope.
     *
     * @param array<string, mixed> $options Any of: limit.
     */
    public function similar($property_id, array $options = []): mixed
    {
        return $this->api->similarProperties($property_id, ...$options);
    }

    /**
     * Search properties
     *
     * Requires the `properties:read` scope.
     */
    public function search($search_request): mixed
    {
        return $this->api->searchProperties($search_request);
    }
}
