<?php
/**
 * ListingInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Skautik\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Skautik\Sdk\Model;

use \ArrayAccess;
use \Skautik\Sdk\ObjectSerializer;

/**
 * ListingInput Class Doc Comment
 *
 * @category Class
 * @package  Skautik\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ListingInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ListingInput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'commission_amount' => 'float',
        'commission_note' => 'string',
        'commission_payer' => 'string',
        'commission_percent' => 'float',
        'currency' => 'string',
        'deposit' => 'float',
        'heating_costs' => 'float',
        'price' => 'float',
        'price_on_request' => 'bool',
        'price_period' => 'string',
        'service_charges' => 'float',
        'status' => 'string',
        'total_rent' => 'float',
        'transaction_type' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'commission_amount' => null,
        'commission_note' => null,
        'commission_payer' => null,
        'commission_percent' => null,
        'currency' => null,
        'deposit' => null,
        'heating_costs' => null,
        'price' => null,
        'price_on_request' => null,
        'price_period' => null,
        'service_charges' => null,
        'status' => null,
        'total_rent' => null,
        'transaction_type' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'commission_amount' => false,
        'commission_note' => false,
        'commission_payer' => false,
        'commission_percent' => false,
        'currency' => false,
        'deposit' => false,
        'heating_costs' => false,
        'price' => false,
        'price_on_request' => false,
        'price_period' => false,
        'service_charges' => false,
        'status' => false,
        'total_rent' => false,
        'transaction_type' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'commission_amount' => 'commission_amount',
        'commission_note' => 'commission_note',
        'commission_payer' => 'commission_payer',
        'commission_percent' => 'commission_percent',
        'currency' => 'currency',
        'deposit' => 'deposit',
        'heating_costs' => 'heating_costs',
        'price' => 'price',
        'price_on_request' => 'price_on_request',
        'price_period' => 'price_period',
        'service_charges' => 'service_charges',
        'status' => 'status',
        'total_rent' => 'total_rent',
        'transaction_type' => 'transaction_type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'commission_amount' => 'setCommissionAmount',
        'commission_note' => 'setCommissionNote',
        'commission_payer' => 'setCommissionPayer',
        'commission_percent' => 'setCommissionPercent',
        'currency' => 'setCurrency',
        'deposit' => 'setDeposit',
        'heating_costs' => 'setHeatingCosts',
        'price' => 'setPrice',
        'price_on_request' => 'setPriceOnRequest',
        'price_period' => 'setPricePeriod',
        'service_charges' => 'setServiceCharges',
        'status' => 'setStatus',
        'total_rent' => 'setTotalRent',
        'transaction_type' => 'setTransactionType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'commission_amount' => 'getCommissionAmount',
        'commission_note' => 'getCommissionNote',
        'commission_payer' => 'getCommissionPayer',
        'commission_percent' => 'getCommissionPercent',
        'currency' => 'getCurrency',
        'deposit' => 'getDeposit',
        'heating_costs' => 'getHeatingCosts',
        'price' => 'getPrice',
        'price_on_request' => 'getPriceOnRequest',
        'price_period' => 'getPricePeriod',
        'service_charges' => 'getServiceCharges',
        'status' => 'getStatus',
        'total_rent' => 'getTotalRent',
        'transaction_type' => 'getTransactionType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('commission_amount', $data ?? [], null);
        $this->setIfExists('commission_note', $data ?? [], null);
        $this->setIfExists('commission_payer', $data ?? [], null);
        $this->setIfExists('commission_percent', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('deposit', $data ?? [], null);
        $this->setIfExists('heating_costs', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('price_on_request', $data ?? [], null);
        $this->setIfExists('price_period', $data ?? [], null);
        $this->setIfExists('service_charges', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('total_rent', $data ?? [], null);
        $this->setIfExists('transaction_type', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets commission_amount
     *
     * @return float|null
     */
    public function getCommissionAmount()
    {
        return $this->container['commission_amount'];
    }

    /**
     * Sets commission_amount
     *
     * @param float|null $commission_amount commission_amount
     *
     * @return self
     */
    public function setCommissionAmount($commission_amount)
    {
        if (is_null($commission_amount)) {
            throw new \InvalidArgumentException('non-nullable commission_amount cannot be null');
        }
        $this->container['commission_amount'] = $commission_amount;

        return $this;
    }

    /**
     * Gets commission_note
     *
     * @return string|null
     */
    public function getCommissionNote()
    {
        return $this->container['commission_note'];
    }

    /**
     * Sets commission_note
     *
     * @param string|null $commission_note commission_note
     *
     * @return self
     */
    public function setCommissionNote($commission_note)
    {
        if (is_null($commission_note)) {
            throw new \InvalidArgumentException('non-nullable commission_note cannot be null');
        }
        $this->container['commission_note'] = $commission_note;

        return $this;
    }

    /**
     * Gets commission_payer
     *
     * @return string|null
     */
    public function getCommissionPayer()
    {
        return $this->container['commission_payer'];
    }

    /**
     * Sets commission_payer
     *
     * @param string|null $commission_payer commission_payer
     *
     * @return self
     */
    public function setCommissionPayer($commission_payer)
    {
        if (is_null($commission_payer)) {
            throw new \InvalidArgumentException('non-nullable commission_payer cannot be null');
        }
        $this->container['commission_payer'] = $commission_payer;

        return $this;
    }

    /**
     * Gets commission_percent
     *
     * @return float|null
     */
    public function getCommissionPercent()
    {
        return $this->container['commission_percent'];
    }

    /**
     * Sets commission_percent
     *
     * @param float|null $commission_percent commission_percent
     *
     * @return self
     */
    public function setCommissionPercent($commission_percent)
    {
        if (is_null($commission_percent)) {
            throw new \InvalidArgumentException('non-nullable commission_percent cannot be null');
        }
        $this->container['commission_percent'] = $commission_percent;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets deposit
     *
     * @return float|null
     */
    public function getDeposit()
    {
        return $this->container['deposit'];
    }

    /**
     * Sets deposit
     *
     * @param float|null $deposit deposit
     *
     * @return self
     */
    public function setDeposit($deposit)
    {
        if (is_null($deposit)) {
            throw new \InvalidArgumentException('non-nullable deposit cannot be null');
        }
        $this->container['deposit'] = $deposit;

        return $this;
    }

    /**
     * Gets heating_costs
     *
     * @return float|null
     */
    public function getHeatingCosts()
    {
        return $this->container['heating_costs'];
    }

    /**
     * Sets heating_costs
     *
     * @param float|null $heating_costs heating_costs
     *
     * @return self
     */
    public function setHeatingCosts($heating_costs)
    {
        if (is_null($heating_costs)) {
            throw new \InvalidArgumentException('non-nullable heating_costs cannot be null');
        }
        $this->container['heating_costs'] = $heating_costs;

        return $this;
    }

    /**
     * Gets price
     *
     * @return float|null
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param float|null $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets price_on_request
     *
     * @return bool|null
     */
    public function getPriceOnRequest()
    {
        return $this->container['price_on_request'];
    }

    /**
     * Sets price_on_request
     *
     * @param bool|null $price_on_request price_on_request
     *
     * @return self
     */
    public function setPriceOnRequest($price_on_request)
    {
        if (is_null($price_on_request)) {
            throw new \InvalidArgumentException('non-nullable price_on_request cannot be null');
        }
        $this->container['price_on_request'] = $price_on_request;

        return $this;
    }

    /**
     * Gets price_period
     *
     * @return string|null
     */
    public function getPricePeriod()
    {
        return $this->container['price_period'];
    }

    /**
     * Sets price_period
     *
     * @param string|null $price_period price_period
     *
     * @return self
     */
    public function setPricePeriod($price_period)
    {
        if (is_null($price_period)) {
            throw new \InvalidArgumentException('non-nullable price_period cannot be null');
        }
        $this->container['price_period'] = $price_period;

        return $this;
    }

    /**
     * Gets service_charges
     *
     * @return float|null
     */
    public function getServiceCharges()
    {
        return $this->container['service_charges'];
    }

    /**
     * Sets service_charges
     *
     * @param float|null $service_charges service_charges
     *
     * @return self
     */
    public function setServiceCharges($service_charges)
    {
        if (is_null($service_charges)) {
            throw new \InvalidArgumentException('non-nullable service_charges cannot be null');
        }
        $this->container['service_charges'] = $service_charges;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets total_rent
     *
     * @return float|null
     */
    public function getTotalRent()
    {
        return $this->container['total_rent'];
    }

    /**
     * Sets total_rent
     *
     * @param float|null $total_rent total_rent
     *
     * @return self
     */
    public function setTotalRent($total_rent)
    {
        if (is_null($total_rent)) {
            throw new \InvalidArgumentException('non-nullable total_rent cannot be null');
        }
        $this->container['total_rent'] = $total_rent;

        return $this;
    }

    /**
     * Gets transaction_type
     *
     * @return string|null
     */
    public function getTransactionType()
    {
        return $this->container['transaction_type'];
    }

    /**
     * Sets transaction_type
     *
     * @param string|null $transaction_type transaction_type
     *
     * @return self
     */
    public function setTransactionType($transaction_type)
    {
        if (is_null($transaction_type)) {
            throw new \InvalidArgumentException('non-nullable transaction_type cannot be null');
        }
        $this->container['transaction_type'] = $transaction_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


