<?php
/**
 * PropertyInput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Skautik\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Skautik\Sdk\Model;

use \ArrayAccess;
use \Skautik\Sdk\ObjectSerializer;

/**
 * PropertyInput Class Doc Comment
 *
 * @category Class
 * @package  Skautik\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PropertyInput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PropertyInput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'address_city' => 'string',
        'address_country' => 'string',
        'address_district' => 'string',
        'address_number' => 'string',
        'address_postal_code' => 'string',
        'address_province' => 'string',
        'address_street' => 'string',
        'attic_sqm' => 'float',
        'balcony_count' => 'int',
        'balcony_terrace_sqm' => 'float',
        'bathrooms' => 'int',
        'bedrooms' => 'int',
        'building_amenities' => 'string[]',
        'cellar_sqm' => 'float',
        'condition' => 'string',
        'construction_phase' => 'string',
        'construction_type' => 'string',
        'description' => 'string',
        'description_fittings' => 'string',
        'description_location' => 'string',
        'description_other' => 'string',
        'energy_certificate_issued_at' => 'string',
        'energy_certificate_type' => 'string',
        'energy_certificate_valid_until' => 'string',
        'energy_co2_emissions' => 'float',
        'energy_consumption_kwh' => 'float',
        'energy_demand_kwh' => 'float',
        'energy_includes_hot_water' => 'bool',
        'energy_label' => 'string',
        'energy_primary_carrier' => 'string',
        'exterior_features' => 'string[]',
        'external_id' => 'string',
        'floor' => 'int',
        'flooring' => 'string',
        'floors_in_building' => 'int',
        'garden_sqm' => 'float',
        'half_bathrooms' => 'int',
        'has_air_conditioning' => 'bool',
        'has_alarm_system' => 'bool',
        'has_balcony' => 'bool',
        'has_cellar' => 'bool',
        'has_fireplace' => 'bool',
        'has_fitted_kitchen' => 'bool',
        'has_garden' => 'bool',
        'has_guest_toilet' => 'bool',
        'has_lift' => 'bool',
        'has_pool' => 'bool',
        'has_sauna' => 'bool',
        'has_solar_panels' => 'bool',
        'has_terrace' => 'bool',
        'heating_type' => 'string',
        'images' => '\Skautik\Sdk\Model\ImageInput[]',
        'interior_features' => 'string[]',
        'is_barrier_free' => 'bool',
        'is_furnished' => 'bool',
        'is_leasehold' => 'bool',
        'is_monument_protected' => 'bool',
        'kitchen_type' => 'string',
        'latitude' => 'float',
        'listing' => '\Skautik\Sdk\Model\ListingInput',
        'living_area_sqm' => 'float',
        'location_precision' => 'string',
        'longitude' => 'float',
        'office_area_sqm' => 'float',
        'other_area_sqm' => 'float',
        'parking_included' => 'bool',
        'parking_space_count' => 'int',
        'parking_type' => 'string',
        'plot_area_sqm' => 'float',
        'property_subtype' => 'string',
        'publish_address' => 'bool',
        'retail_area_sqm' => 'float',
        'storage_area_sqm' => 'float',
        'surroundings' => 'string[]',
        'terrace_count' => 'int',
        'title' => 'string',
        'total_area_sqm' => 'float',
        'total_rooms' => 'int',
        'translations' => '\Skautik\Sdk\Model\Translation[]',
        'type' => 'string',
        'usable_area_sqm' => 'float',
        'window_glazing' => 'string',
        'year_built' => 'int',
        'year_renovated' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'address_city' => null,
        'address_country' => null,
        'address_district' => null,
        'address_number' => null,
        'address_postal_code' => null,
        'address_province' => null,
        'address_street' => null,
        'attic_sqm' => null,
        'balcony_count' => null,
        'balcony_terrace_sqm' => null,
        'bathrooms' => null,
        'bedrooms' => null,
        'building_amenities' => null,
        'cellar_sqm' => null,
        'condition' => null,
        'construction_phase' => null,
        'construction_type' => null,
        'description' => null,
        'description_fittings' => null,
        'description_location' => null,
        'description_other' => null,
        'energy_certificate_issued_at' => null,
        'energy_certificate_type' => null,
        'energy_certificate_valid_until' => null,
        'energy_co2_emissions' => null,
        'energy_consumption_kwh' => null,
        'energy_demand_kwh' => null,
        'energy_includes_hot_water' => null,
        'energy_label' => null,
        'energy_primary_carrier' => null,
        'exterior_features' => null,
        'external_id' => null,
        'floor' => null,
        'flooring' => null,
        'floors_in_building' => null,
        'garden_sqm' => null,
        'half_bathrooms' => null,
        'has_air_conditioning' => null,
        'has_alarm_system' => null,
        'has_balcony' => null,
        'has_cellar' => null,
        'has_fireplace' => null,
        'has_fitted_kitchen' => null,
        'has_garden' => null,
        'has_guest_toilet' => null,
        'has_lift' => null,
        'has_pool' => null,
        'has_sauna' => null,
        'has_solar_panels' => null,
        'has_terrace' => null,
        'heating_type' => null,
        'images' => null,
        'interior_features' => null,
        'is_barrier_free' => null,
        'is_furnished' => null,
        'is_leasehold' => null,
        'is_monument_protected' => null,
        'kitchen_type' => null,
        'latitude' => null,
        'listing' => null,
        'living_area_sqm' => null,
        'location_precision' => null,
        'longitude' => null,
        'office_area_sqm' => null,
        'other_area_sqm' => null,
        'parking_included' => null,
        'parking_space_count' => null,
        'parking_type' => null,
        'plot_area_sqm' => null,
        'property_subtype' => null,
        'publish_address' => null,
        'retail_area_sqm' => null,
        'storage_area_sqm' => null,
        'surroundings' => null,
        'terrace_count' => null,
        'title' => null,
        'total_area_sqm' => null,
        'total_rooms' => null,
        'translations' => null,
        'type' => null,
        'usable_area_sqm' => null,
        'window_glazing' => null,
        'year_built' => null,
        'year_renovated' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'address_city' => false,
        'address_country' => false,
        'address_district' => false,
        'address_number' => false,
        'address_postal_code' => false,
        'address_province' => false,
        'address_street' => false,
        'attic_sqm' => false,
        'balcony_count' => false,
        'balcony_terrace_sqm' => false,
        'bathrooms' => false,
        'bedrooms' => false,
        'building_amenities' => false,
        'cellar_sqm' => false,
        'condition' => false,
        'construction_phase' => false,
        'construction_type' => false,
        'description' => false,
        'description_fittings' => false,
        'description_location' => false,
        'description_other' => false,
        'energy_certificate_issued_at' => false,
        'energy_certificate_type' => false,
        'energy_certificate_valid_until' => false,
        'energy_co2_emissions' => false,
        'energy_consumption_kwh' => false,
        'energy_demand_kwh' => false,
        'energy_includes_hot_water' => false,
        'energy_label' => false,
        'energy_primary_carrier' => false,
        'exterior_features' => false,
        'external_id' => false,
        'floor' => false,
        'flooring' => false,
        'floors_in_building' => false,
        'garden_sqm' => false,
        'half_bathrooms' => false,
        'has_air_conditioning' => false,
        'has_alarm_system' => false,
        'has_balcony' => false,
        'has_cellar' => false,
        'has_fireplace' => false,
        'has_fitted_kitchen' => false,
        'has_garden' => false,
        'has_guest_toilet' => false,
        'has_lift' => false,
        'has_pool' => false,
        'has_sauna' => false,
        'has_solar_panels' => false,
        'has_terrace' => false,
        'heating_type' => false,
        'images' => false,
        'interior_features' => false,
        'is_barrier_free' => false,
        'is_furnished' => false,
        'is_leasehold' => false,
        'is_monument_protected' => false,
        'kitchen_type' => false,
        'latitude' => false,
        'listing' => false,
        'living_area_sqm' => false,
        'location_precision' => false,
        'longitude' => false,
        'office_area_sqm' => false,
        'other_area_sqm' => false,
        'parking_included' => false,
        'parking_space_count' => false,
        'parking_type' => false,
        'plot_area_sqm' => false,
        'property_subtype' => false,
        'publish_address' => false,
        'retail_area_sqm' => false,
        'storage_area_sqm' => false,
        'surroundings' => false,
        'terrace_count' => false,
        'title' => false,
        'total_area_sqm' => false,
        'total_rooms' => false,
        'translations' => false,
        'type' => false,
        'usable_area_sqm' => false,
        'window_glazing' => false,
        'year_built' => false,
        'year_renovated' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address_city' => 'address_city',
        'address_country' => 'address_country',
        'address_district' => 'address_district',
        'address_number' => 'address_number',
        'address_postal_code' => 'address_postal_code',
        'address_province' => 'address_province',
        'address_street' => 'address_street',
        'attic_sqm' => 'attic_sqm',
        'balcony_count' => 'balcony_count',
        'balcony_terrace_sqm' => 'balcony_terrace_sqm',
        'bathrooms' => 'bathrooms',
        'bedrooms' => 'bedrooms',
        'building_amenities' => 'building_amenities',
        'cellar_sqm' => 'cellar_sqm',
        'condition' => 'condition',
        'construction_phase' => 'construction_phase',
        'construction_type' => 'construction_type',
        'description' => 'description',
        'description_fittings' => 'description_fittings',
        'description_location' => 'description_location',
        'description_other' => 'description_other',
        'energy_certificate_issued_at' => 'energy_certificate_issued_at',
        'energy_certificate_type' => 'energy_certificate_type',
        'energy_certificate_valid_until' => 'energy_certificate_valid_until',
        'energy_co2_emissions' => 'energy_co2_emissions',
        'energy_consumption_kwh' => 'energy_consumption_kwh',
        'energy_demand_kwh' => 'energy_demand_kwh',
        'energy_includes_hot_water' => 'energy_includes_hot_water',
        'energy_label' => 'energy_label',
        'energy_primary_carrier' => 'energy_primary_carrier',
        'exterior_features' => 'exterior_features',
        'external_id' => 'external_id',
        'floor' => 'floor',
        'flooring' => 'flooring',
        'floors_in_building' => 'floors_in_building',
        'garden_sqm' => 'garden_sqm',
        'half_bathrooms' => 'half_bathrooms',
        'has_air_conditioning' => 'has_air_conditioning',
        'has_alarm_system' => 'has_alarm_system',
        'has_balcony' => 'has_balcony',
        'has_cellar' => 'has_cellar',
        'has_fireplace' => 'has_fireplace',
        'has_fitted_kitchen' => 'has_fitted_kitchen',
        'has_garden' => 'has_garden',
        'has_guest_toilet' => 'has_guest_toilet',
        'has_lift' => 'has_lift',
        'has_pool' => 'has_pool',
        'has_sauna' => 'has_sauna',
        'has_solar_panels' => 'has_solar_panels',
        'has_terrace' => 'has_terrace',
        'heating_type' => 'heating_type',
        'images' => 'images',
        'interior_features' => 'interior_features',
        'is_barrier_free' => 'is_barrier_free',
        'is_furnished' => 'is_furnished',
        'is_leasehold' => 'is_leasehold',
        'is_monument_protected' => 'is_monument_protected',
        'kitchen_type' => 'kitchen_type',
        'latitude' => 'latitude',
        'listing' => 'listing',
        'living_area_sqm' => 'living_area_sqm',
        'location_precision' => 'location_precision',
        'longitude' => 'longitude',
        'office_area_sqm' => 'office_area_sqm',
        'other_area_sqm' => 'other_area_sqm',
        'parking_included' => 'parking_included',
        'parking_space_count' => 'parking_space_count',
        'parking_type' => 'parking_type',
        'plot_area_sqm' => 'plot_area_sqm',
        'property_subtype' => 'property_subtype',
        'publish_address' => 'publish_address',
        'retail_area_sqm' => 'retail_area_sqm',
        'storage_area_sqm' => 'storage_area_sqm',
        'surroundings' => 'surroundings',
        'terrace_count' => 'terrace_count',
        'title' => 'title',
        'total_area_sqm' => 'total_area_sqm',
        'total_rooms' => 'total_rooms',
        'translations' => 'translations',
        'type' => 'type',
        'usable_area_sqm' => 'usable_area_sqm',
        'window_glazing' => 'window_glazing',
        'year_built' => 'year_built',
        'year_renovated' => 'year_renovated'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'address_city' => 'setAddressCity',
        'address_country' => 'setAddressCountry',
        'address_district' => 'setAddressDistrict',
        'address_number' => 'setAddressNumber',
        'address_postal_code' => 'setAddressPostalCode',
        'address_province' => 'setAddressProvince',
        'address_street' => 'setAddressStreet',
        'attic_sqm' => 'setAtticSqm',
        'balcony_count' => 'setBalconyCount',
        'balcony_terrace_sqm' => 'setBalconyTerraceSqm',
        'bathrooms' => 'setBathrooms',
        'bedrooms' => 'setBedrooms',
        'building_amenities' => 'setBuildingAmenities',
        'cellar_sqm' => 'setCellarSqm',
        'condition' => 'setCondition',
        'construction_phase' => 'setConstructionPhase',
        'construction_type' => 'setConstructionType',
        'description' => 'setDescription',
        'description_fittings' => 'setDescriptionFittings',
        'description_location' => 'setDescriptionLocation',
        'description_other' => 'setDescriptionOther',
        'energy_certificate_issued_at' => 'setEnergyCertificateIssuedAt',
        'energy_certificate_type' => 'setEnergyCertificateType',
        'energy_certificate_valid_until' => 'setEnergyCertificateValidUntil',
        'energy_co2_emissions' => 'setEnergyCo2Emissions',
        'energy_consumption_kwh' => 'setEnergyConsumptionKwh',
        'energy_demand_kwh' => 'setEnergyDemandKwh',
        'energy_includes_hot_water' => 'setEnergyIncludesHotWater',
        'energy_label' => 'setEnergyLabel',
        'energy_primary_carrier' => 'setEnergyPrimaryCarrier',
        'exterior_features' => 'setExteriorFeatures',
        'external_id' => 'setExternalId',
        'floor' => 'setFloor',
        'flooring' => 'setFlooring',
        'floors_in_building' => 'setFloorsInBuilding',
        'garden_sqm' => 'setGardenSqm',
        'half_bathrooms' => 'setHalfBathrooms',
        'has_air_conditioning' => 'setHasAirConditioning',
        'has_alarm_system' => 'setHasAlarmSystem',
        'has_balcony' => 'setHasBalcony',
        'has_cellar' => 'setHasCellar',
        'has_fireplace' => 'setHasFireplace',
        'has_fitted_kitchen' => 'setHasFittedKitchen',
        'has_garden' => 'setHasGarden',
        'has_guest_toilet' => 'setHasGuestToilet',
        'has_lift' => 'setHasLift',
        'has_pool' => 'setHasPool',
        'has_sauna' => 'setHasSauna',
        'has_solar_panels' => 'setHasSolarPanels',
        'has_terrace' => 'setHasTerrace',
        'heating_type' => 'setHeatingType',
        'images' => 'setImages',
        'interior_features' => 'setInteriorFeatures',
        'is_barrier_free' => 'setIsBarrierFree',
        'is_furnished' => 'setIsFurnished',
        'is_leasehold' => 'setIsLeasehold',
        'is_monument_protected' => 'setIsMonumentProtected',
        'kitchen_type' => 'setKitchenType',
        'latitude' => 'setLatitude',
        'listing' => 'setListing',
        'living_area_sqm' => 'setLivingAreaSqm',
        'location_precision' => 'setLocationPrecision',
        'longitude' => 'setLongitude',
        'office_area_sqm' => 'setOfficeAreaSqm',
        'other_area_sqm' => 'setOtherAreaSqm',
        'parking_included' => 'setParkingIncluded',
        'parking_space_count' => 'setParkingSpaceCount',
        'parking_type' => 'setParkingType',
        'plot_area_sqm' => 'setPlotAreaSqm',
        'property_subtype' => 'setPropertySubtype',
        'publish_address' => 'setPublishAddress',
        'retail_area_sqm' => 'setRetailAreaSqm',
        'storage_area_sqm' => 'setStorageAreaSqm',
        'surroundings' => 'setSurroundings',
        'terrace_count' => 'setTerraceCount',
        'title' => 'setTitle',
        'total_area_sqm' => 'setTotalAreaSqm',
        'total_rooms' => 'setTotalRooms',
        'translations' => 'setTranslations',
        'type' => 'setType',
        'usable_area_sqm' => 'setUsableAreaSqm',
        'window_glazing' => 'setWindowGlazing',
        'year_built' => 'setYearBuilt',
        'year_renovated' => 'setYearRenovated'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'address_city' => 'getAddressCity',
        'address_country' => 'getAddressCountry',
        'address_district' => 'getAddressDistrict',
        'address_number' => 'getAddressNumber',
        'address_postal_code' => 'getAddressPostalCode',
        'address_province' => 'getAddressProvince',
        'address_street' => 'getAddressStreet',
        'attic_sqm' => 'getAtticSqm',
        'balcony_count' => 'getBalconyCount',
        'balcony_terrace_sqm' => 'getBalconyTerraceSqm',
        'bathrooms' => 'getBathrooms',
        'bedrooms' => 'getBedrooms',
        'building_amenities' => 'getBuildingAmenities',
        'cellar_sqm' => 'getCellarSqm',
        'condition' => 'getCondition',
        'construction_phase' => 'getConstructionPhase',
        'construction_type' => 'getConstructionType',
        'description' => 'getDescription',
        'description_fittings' => 'getDescriptionFittings',
        'description_location' => 'getDescriptionLocation',
        'description_other' => 'getDescriptionOther',
        'energy_certificate_issued_at' => 'getEnergyCertificateIssuedAt',
        'energy_certificate_type' => 'getEnergyCertificateType',
        'energy_certificate_valid_until' => 'getEnergyCertificateValidUntil',
        'energy_co2_emissions' => 'getEnergyCo2Emissions',
        'energy_consumption_kwh' => 'getEnergyConsumptionKwh',
        'energy_demand_kwh' => 'getEnergyDemandKwh',
        'energy_includes_hot_water' => 'getEnergyIncludesHotWater',
        'energy_label' => 'getEnergyLabel',
        'energy_primary_carrier' => 'getEnergyPrimaryCarrier',
        'exterior_features' => 'getExteriorFeatures',
        'external_id' => 'getExternalId',
        'floor' => 'getFloor',
        'flooring' => 'getFlooring',
        'floors_in_building' => 'getFloorsInBuilding',
        'garden_sqm' => 'getGardenSqm',
        'half_bathrooms' => 'getHalfBathrooms',
        'has_air_conditioning' => 'getHasAirConditioning',
        'has_alarm_system' => 'getHasAlarmSystem',
        'has_balcony' => 'getHasBalcony',
        'has_cellar' => 'getHasCellar',
        'has_fireplace' => 'getHasFireplace',
        'has_fitted_kitchen' => 'getHasFittedKitchen',
        'has_garden' => 'getHasGarden',
        'has_guest_toilet' => 'getHasGuestToilet',
        'has_lift' => 'getHasLift',
        'has_pool' => 'getHasPool',
        'has_sauna' => 'getHasSauna',
        'has_solar_panels' => 'getHasSolarPanels',
        'has_terrace' => 'getHasTerrace',
        'heating_type' => 'getHeatingType',
        'images' => 'getImages',
        'interior_features' => 'getInteriorFeatures',
        'is_barrier_free' => 'getIsBarrierFree',
        'is_furnished' => 'getIsFurnished',
        'is_leasehold' => 'getIsLeasehold',
        'is_monument_protected' => 'getIsMonumentProtected',
        'kitchen_type' => 'getKitchenType',
        'latitude' => 'getLatitude',
        'listing' => 'getListing',
        'living_area_sqm' => 'getLivingAreaSqm',
        'location_precision' => 'getLocationPrecision',
        'longitude' => 'getLongitude',
        'office_area_sqm' => 'getOfficeAreaSqm',
        'other_area_sqm' => 'getOtherAreaSqm',
        'parking_included' => 'getParkingIncluded',
        'parking_space_count' => 'getParkingSpaceCount',
        'parking_type' => 'getParkingType',
        'plot_area_sqm' => 'getPlotAreaSqm',
        'property_subtype' => 'getPropertySubtype',
        'publish_address' => 'getPublishAddress',
        'retail_area_sqm' => 'getRetailAreaSqm',
        'storage_area_sqm' => 'getStorageAreaSqm',
        'surroundings' => 'getSurroundings',
        'terrace_count' => 'getTerraceCount',
        'title' => 'getTitle',
        'total_area_sqm' => 'getTotalAreaSqm',
        'total_rooms' => 'getTotalRooms',
        'translations' => 'getTranslations',
        'type' => 'getType',
        'usable_area_sqm' => 'getUsableAreaSqm',
        'window_glazing' => 'getWindowGlazing',
        'year_built' => 'getYearBuilt',
        'year_renovated' => 'getYearRenovated'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('address_city', $data ?? [], null);
        $this->setIfExists('address_country', $data ?? [], null);
        $this->setIfExists('address_district', $data ?? [], null);
        $this->setIfExists('address_number', $data ?? [], null);
        $this->setIfExists('address_postal_code', $data ?? [], null);
        $this->setIfExists('address_province', $data ?? [], null);
        $this->setIfExists('address_street', $data ?? [], null);
        $this->setIfExists('attic_sqm', $data ?? [], null);
        $this->setIfExists('balcony_count', $data ?? [], null);
        $this->setIfExists('balcony_terrace_sqm', $data ?? [], null);
        $this->setIfExists('bathrooms', $data ?? [], null);
        $this->setIfExists('bedrooms', $data ?? [], null);
        $this->setIfExists('building_amenities', $data ?? [], null);
        $this->setIfExists('cellar_sqm', $data ?? [], null);
        $this->setIfExists('condition', $data ?? [], null);
        $this->setIfExists('construction_phase', $data ?? [], null);
        $this->setIfExists('construction_type', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('description_fittings', $data ?? [], null);
        $this->setIfExists('description_location', $data ?? [], null);
        $this->setIfExists('description_other', $data ?? [], null);
        $this->setIfExists('energy_certificate_issued_at', $data ?? [], null);
        $this->setIfExists('energy_certificate_type', $data ?? [], null);
        $this->setIfExists('energy_certificate_valid_until', $data ?? [], null);
        $this->setIfExists('energy_co2_emissions', $data ?? [], null);
        $this->setIfExists('energy_consumption_kwh', $data ?? [], null);
        $this->setIfExists('energy_demand_kwh', $data ?? [], null);
        $this->setIfExists('energy_includes_hot_water', $data ?? [], null);
        $this->setIfExists('energy_label', $data ?? [], null);
        $this->setIfExists('energy_primary_carrier', $data ?? [], null);
        $this->setIfExists('exterior_features', $data ?? [], null);
        $this->setIfExists('external_id', $data ?? [], null);
        $this->setIfExists('floor', $data ?? [], null);
        $this->setIfExists('flooring', $data ?? [], null);
        $this->setIfExists('floors_in_building', $data ?? [], null);
        $this->setIfExists('garden_sqm', $data ?? [], null);
        $this->setIfExists('half_bathrooms', $data ?? [], null);
        $this->setIfExists('has_air_conditioning', $data ?? [], null);
        $this->setIfExists('has_alarm_system', $data ?? [], null);
        $this->setIfExists('has_balcony', $data ?? [], null);
        $this->setIfExists('has_cellar', $data ?? [], null);
        $this->setIfExists('has_fireplace', $data ?? [], null);
        $this->setIfExists('has_fitted_kitchen', $data ?? [], null);
        $this->setIfExists('has_garden', $data ?? [], null);
        $this->setIfExists('has_guest_toilet', $data ?? [], null);
        $this->setIfExists('has_lift', $data ?? [], null);
        $this->setIfExists('has_pool', $data ?? [], null);
        $this->setIfExists('has_sauna', $data ?? [], null);
        $this->setIfExists('has_solar_panels', $data ?? [], null);
        $this->setIfExists('has_terrace', $data ?? [], null);
        $this->setIfExists('heating_type', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('interior_features', $data ?? [], null);
        $this->setIfExists('is_barrier_free', $data ?? [], null);
        $this->setIfExists('is_furnished', $data ?? [], null);
        $this->setIfExists('is_leasehold', $data ?? [], null);
        $this->setIfExists('is_monument_protected', $data ?? [], null);
        $this->setIfExists('kitchen_type', $data ?? [], null);
        $this->setIfExists('latitude', $data ?? [], null);
        $this->setIfExists('listing', $data ?? [], null);
        $this->setIfExists('living_area_sqm', $data ?? [], null);
        $this->setIfExists('location_precision', $data ?? [], null);
        $this->setIfExists('longitude', $data ?? [], null);
        $this->setIfExists('office_area_sqm', $data ?? [], null);
        $this->setIfExists('other_area_sqm', $data ?? [], null);
        $this->setIfExists('parking_included', $data ?? [], null);
        $this->setIfExists('parking_space_count', $data ?? [], null);
        $this->setIfExists('parking_type', $data ?? [], null);
        $this->setIfExists('plot_area_sqm', $data ?? [], null);
        $this->setIfExists('property_subtype', $data ?? [], null);
        $this->setIfExists('publish_address', $data ?? [], null);
        $this->setIfExists('retail_area_sqm', $data ?? [], null);
        $this->setIfExists('storage_area_sqm', $data ?? [], null);
        $this->setIfExists('surroundings', $data ?? [], null);
        $this->setIfExists('terrace_count', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('total_area_sqm', $data ?? [], null);
        $this->setIfExists('total_rooms', $data ?? [], null);
        $this->setIfExists('translations', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('usable_area_sqm', $data ?? [], null);
        $this->setIfExists('window_glazing', $data ?? [], null);
        $this->setIfExists('year_built', $data ?? [], null);
        $this->setIfExists('year_renovated', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address_city
     *
     * @return string|null
     */
    public function getAddressCity()
    {
        return $this->container['address_city'];
    }

    /**
     * Sets address_city
     *
     * @param string|null $address_city address_city
     *
     * @return self
     */
    public function setAddressCity($address_city)
    {
        if (is_null($address_city)) {
            throw new \InvalidArgumentException('non-nullable address_city cannot be null');
        }
        $this->container['address_city'] = $address_city;

        return $this;
    }

    /**
     * Gets address_country
     *
     * @return string|null
     */
    public function getAddressCountry()
    {
        return $this->container['address_country'];
    }

    /**
     * Sets address_country
     *
     * @param string|null $address_country address_country
     *
     * @return self
     */
    public function setAddressCountry($address_country)
    {
        if (is_null($address_country)) {
            throw new \InvalidArgumentException('non-nullable address_country cannot be null');
        }
        $this->container['address_country'] = $address_country;

        return $this;
    }

    /**
     * Gets address_district
     *
     * @return string|null
     */
    public function getAddressDistrict()
    {
        return $this->container['address_district'];
    }

    /**
     * Sets address_district
     *
     * @param string|null $address_district address_district
     *
     * @return self
     */
    public function setAddressDistrict($address_district)
    {
        if (is_null($address_district)) {
            throw new \InvalidArgumentException('non-nullable address_district cannot be null');
        }
        $this->container['address_district'] = $address_district;

        return $this;
    }

    /**
     * Gets address_number
     *
     * @return string|null
     */
    public function getAddressNumber()
    {
        return $this->container['address_number'];
    }

    /**
     * Sets address_number
     *
     * @param string|null $address_number address_number
     *
     * @return self
     */
    public function setAddressNumber($address_number)
    {
        if (is_null($address_number)) {
            throw new \InvalidArgumentException('non-nullable address_number cannot be null');
        }
        $this->container['address_number'] = $address_number;

        return $this;
    }

    /**
     * Gets address_postal_code
     *
     * @return string|null
     */
    public function getAddressPostalCode()
    {
        return $this->container['address_postal_code'];
    }

    /**
     * Sets address_postal_code
     *
     * @param string|null $address_postal_code address_postal_code
     *
     * @return self
     */
    public function setAddressPostalCode($address_postal_code)
    {
        if (is_null($address_postal_code)) {
            throw new \InvalidArgumentException('non-nullable address_postal_code cannot be null');
        }
        $this->container['address_postal_code'] = $address_postal_code;

        return $this;
    }

    /**
     * Gets address_province
     *
     * @return string|null
     */
    public function getAddressProvince()
    {
        return $this->container['address_province'];
    }

    /**
     * Sets address_province
     *
     * @param string|null $address_province address_province
     *
     * @return self
     */
    public function setAddressProvince($address_province)
    {
        if (is_null($address_province)) {
            throw new \InvalidArgumentException('non-nullable address_province cannot be null');
        }
        $this->container['address_province'] = $address_province;

        return $this;
    }

    /**
     * Gets address_street
     *
     * @return string|null
     */
    public function getAddressStreet()
    {
        return $this->container['address_street'];
    }

    /**
     * Sets address_street
     *
     * @param string|null $address_street address_street
     *
     * @return self
     */
    public function setAddressStreet($address_street)
    {
        if (is_null($address_street)) {
            throw new \InvalidArgumentException('non-nullable address_street cannot be null');
        }
        $this->container['address_street'] = $address_street;

        return $this;
    }

    /**
     * Gets attic_sqm
     *
     * @return float|null
     */
    public function getAtticSqm()
    {
        return $this->container['attic_sqm'];
    }

    /**
     * Sets attic_sqm
     *
     * @param float|null $attic_sqm attic_sqm
     *
     * @return self
     */
    public function setAtticSqm($attic_sqm)
    {
        if (is_null($attic_sqm)) {
            throw new \InvalidArgumentException('non-nullable attic_sqm cannot be null');
        }
        $this->container['attic_sqm'] = $attic_sqm;

        return $this;
    }

    /**
     * Gets balcony_count
     *
     * @return int|null
     */
    public function getBalconyCount()
    {
        return $this->container['balcony_count'];
    }

    /**
     * Sets balcony_count
     *
     * @param int|null $balcony_count balcony_count
     *
     * @return self
     */
    public function setBalconyCount($balcony_count)
    {
        if (is_null($balcony_count)) {
            throw new \InvalidArgumentException('non-nullable balcony_count cannot be null');
        }
        $this->container['balcony_count'] = $balcony_count;

        return $this;
    }

    /**
     * Gets balcony_terrace_sqm
     *
     * @return float|null
     */
    public function getBalconyTerraceSqm()
    {
        return $this->container['balcony_terrace_sqm'];
    }

    /**
     * Sets balcony_terrace_sqm
     *
     * @param float|null $balcony_terrace_sqm balcony_terrace_sqm
     *
     * @return self
     */
    public function setBalconyTerraceSqm($balcony_terrace_sqm)
    {
        if (is_null($balcony_terrace_sqm)) {
            throw new \InvalidArgumentException('non-nullable balcony_terrace_sqm cannot be null');
        }
        $this->container['balcony_terrace_sqm'] = $balcony_terrace_sqm;

        return $this;
    }

    /**
     * Gets bathrooms
     *
     * @return int|null
     */
    public function getBathrooms()
    {
        return $this->container['bathrooms'];
    }

    /**
     * Sets bathrooms
     *
     * @param int|null $bathrooms bathrooms
     *
     * @return self
     */
    public function setBathrooms($bathrooms)
    {
        if (is_null($bathrooms)) {
            throw new \InvalidArgumentException('non-nullable bathrooms cannot be null');
        }
        $this->container['bathrooms'] = $bathrooms;

        return $this;
    }

    /**
     * Gets bedrooms
     *
     * @return int|null
     */
    public function getBedrooms()
    {
        return $this->container['bedrooms'];
    }

    /**
     * Sets bedrooms
     *
     * @param int|null $bedrooms bedrooms
     *
     * @return self
     */
    public function setBedrooms($bedrooms)
    {
        if (is_null($bedrooms)) {
            throw new \InvalidArgumentException('non-nullable bedrooms cannot be null');
        }
        $this->container['bedrooms'] = $bedrooms;

        return $this;
    }

    /**
     * Gets building_amenities
     *
     * @return string[]|null
     */
    public function getBuildingAmenities()
    {
        return $this->container['building_amenities'];
    }

    /**
     * Sets building_amenities
     *
     * @param string[]|null $building_amenities building_amenities
     *
     * @return self
     */
    public function setBuildingAmenities($building_amenities)
    {
        if (is_null($building_amenities)) {
            throw new \InvalidArgumentException('non-nullable building_amenities cannot be null');
        }
        $this->container['building_amenities'] = $building_amenities;

        return $this;
    }

    /**
     * Gets cellar_sqm
     *
     * @return float|null
     */
    public function getCellarSqm()
    {
        return $this->container['cellar_sqm'];
    }

    /**
     * Sets cellar_sqm
     *
     * @param float|null $cellar_sqm cellar_sqm
     *
     * @return self
     */
    public function setCellarSqm($cellar_sqm)
    {
        if (is_null($cellar_sqm)) {
            throw new \InvalidArgumentException('non-nullable cellar_sqm cannot be null');
        }
        $this->container['cellar_sqm'] = $cellar_sqm;

        return $this;
    }

    /**
     * Gets condition
     *
     * @return string|null
     */
    public function getCondition()
    {
        return $this->container['condition'];
    }

    /**
     * Sets condition
     *
     * @param string|null $condition condition
     *
     * @return self
     */
    public function setCondition($condition)
    {
        if (is_null($condition)) {
            throw new \InvalidArgumentException('non-nullable condition cannot be null');
        }
        $this->container['condition'] = $condition;

        return $this;
    }

    /**
     * Gets construction_phase
     *
     * @return string|null
     */
    public function getConstructionPhase()
    {
        return $this->container['construction_phase'];
    }

    /**
     * Sets construction_phase
     *
     * @param string|null $construction_phase construction_phase
     *
     * @return self
     */
    public function setConstructionPhase($construction_phase)
    {
        if (is_null($construction_phase)) {
            throw new \InvalidArgumentException('non-nullable construction_phase cannot be null');
        }
        $this->container['construction_phase'] = $construction_phase;

        return $this;
    }

    /**
     * Gets construction_type
     *
     * @return string|null
     */
    public function getConstructionType()
    {
        return $this->container['construction_type'];
    }

    /**
     * Sets construction_type
     *
     * @param string|null $construction_type construction_type
     *
     * @return self
     */
    public function setConstructionType($construction_type)
    {
        if (is_null($construction_type)) {
            throw new \InvalidArgumentException('non-nullable construction_type cannot be null');
        }
        $this->container['construction_type'] = $construction_type;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets description_fittings
     *
     * @return string|null
     */
    public function getDescriptionFittings()
    {
        return $this->container['description_fittings'];
    }

    /**
     * Sets description_fittings
     *
     * @param string|null $description_fittings description_fittings
     *
     * @return self
     */
    public function setDescriptionFittings($description_fittings)
    {
        if (is_null($description_fittings)) {
            throw new \InvalidArgumentException('non-nullable description_fittings cannot be null');
        }
        $this->container['description_fittings'] = $description_fittings;

        return $this;
    }

    /**
     * Gets description_location
     *
     * @return string|null
     */
    public function getDescriptionLocation()
    {
        return $this->container['description_location'];
    }

    /**
     * Sets description_location
     *
     * @param string|null $description_location description_location
     *
     * @return self
     */
    public function setDescriptionLocation($description_location)
    {
        if (is_null($description_location)) {
            throw new \InvalidArgumentException('non-nullable description_location cannot be null');
        }
        $this->container['description_location'] = $description_location;

        return $this;
    }

    /**
     * Gets description_other
     *
     * @return string|null
     */
    public function getDescriptionOther()
    {
        return $this->container['description_other'];
    }

    /**
     * Sets description_other
     *
     * @param string|null $description_other description_other
     *
     * @return self
     */
    public function setDescriptionOther($description_other)
    {
        if (is_null($description_other)) {
            throw new \InvalidArgumentException('non-nullable description_other cannot be null');
        }
        $this->container['description_other'] = $description_other;

        return $this;
    }

    /**
     * Gets energy_certificate_issued_at
     *
     * @return string|null
     */
    public function getEnergyCertificateIssuedAt()
    {
        return $this->container['energy_certificate_issued_at'];
    }

    /**
     * Sets energy_certificate_issued_at
     *
     * @param string|null $energy_certificate_issued_at energy_certificate_issued_at
     *
     * @return self
     */
    public function setEnergyCertificateIssuedAt($energy_certificate_issued_at)
    {
        if (is_null($energy_certificate_issued_at)) {
            throw new \InvalidArgumentException('non-nullable energy_certificate_issued_at cannot be null');
        }
        $this->container['energy_certificate_issued_at'] = $energy_certificate_issued_at;

        return $this;
    }

    /**
     * Gets energy_certificate_type
     *
     * @return string|null
     */
    public function getEnergyCertificateType()
    {
        return $this->container['energy_certificate_type'];
    }

    /**
     * Sets energy_certificate_type
     *
     * @param string|null $energy_certificate_type energy_certificate_type
     *
     * @return self
     */
    public function setEnergyCertificateType($energy_certificate_type)
    {
        if (is_null($energy_certificate_type)) {
            throw new \InvalidArgumentException('non-nullable energy_certificate_type cannot be null');
        }
        $this->container['energy_certificate_type'] = $energy_certificate_type;

        return $this;
    }

    /**
     * Gets energy_certificate_valid_until
     *
     * @return string|null
     */
    public function getEnergyCertificateValidUntil()
    {
        return $this->container['energy_certificate_valid_until'];
    }

    /**
     * Sets energy_certificate_valid_until
     *
     * @param string|null $energy_certificate_valid_until energy_certificate_valid_until
     *
     * @return self
     */
    public function setEnergyCertificateValidUntil($energy_certificate_valid_until)
    {
        if (is_null($energy_certificate_valid_until)) {
            throw new \InvalidArgumentException('non-nullable energy_certificate_valid_until cannot be null');
        }
        $this->container['energy_certificate_valid_until'] = $energy_certificate_valid_until;

        return $this;
    }

    /**
     * Gets energy_co2_emissions
     *
     * @return float|null
     */
    public function getEnergyCo2Emissions()
    {
        return $this->container['energy_co2_emissions'];
    }

    /**
     * Sets energy_co2_emissions
     *
     * @param float|null $energy_co2_emissions energy_co2_emissions
     *
     * @return self
     */
    public function setEnergyCo2Emissions($energy_co2_emissions)
    {
        if (is_null($energy_co2_emissions)) {
            throw new \InvalidArgumentException('non-nullable energy_co2_emissions cannot be null');
        }
        $this->container['energy_co2_emissions'] = $energy_co2_emissions;

        return $this;
    }

    /**
     * Gets energy_consumption_kwh
     *
     * @return float|null
     */
    public function getEnergyConsumptionKwh()
    {
        return $this->container['energy_consumption_kwh'];
    }

    /**
     * Sets energy_consumption_kwh
     *
     * @param float|null $energy_consumption_kwh energy_consumption_kwh
     *
     * @return self
     */
    public function setEnergyConsumptionKwh($energy_consumption_kwh)
    {
        if (is_null($energy_consumption_kwh)) {
            throw new \InvalidArgumentException('non-nullable energy_consumption_kwh cannot be null');
        }
        $this->container['energy_consumption_kwh'] = $energy_consumption_kwh;

        return $this;
    }

    /**
     * Gets energy_demand_kwh
     *
     * @return float|null
     */
    public function getEnergyDemandKwh()
    {
        return $this->container['energy_demand_kwh'];
    }

    /**
     * Sets energy_demand_kwh
     *
     * @param float|null $energy_demand_kwh energy_demand_kwh
     *
     * @return self
     */
    public function setEnergyDemandKwh($energy_demand_kwh)
    {
        if (is_null($energy_demand_kwh)) {
            throw new \InvalidArgumentException('non-nullable energy_demand_kwh cannot be null');
        }
        $this->container['energy_demand_kwh'] = $energy_demand_kwh;

        return $this;
    }

    /**
     * Gets energy_includes_hot_water
     *
     * @return bool|null
     */
    public function getEnergyIncludesHotWater()
    {
        return $this->container['energy_includes_hot_water'];
    }

    /**
     * Sets energy_includes_hot_water
     *
     * @param bool|null $energy_includes_hot_water energy_includes_hot_water
     *
     * @return self
     */
    public function setEnergyIncludesHotWater($energy_includes_hot_water)
    {
        if (is_null($energy_includes_hot_water)) {
            throw new \InvalidArgumentException('non-nullable energy_includes_hot_water cannot be null');
        }
        $this->container['energy_includes_hot_water'] = $energy_includes_hot_water;

        return $this;
    }

    /**
     * Gets energy_label
     *
     * @return string|null
     */
    public function getEnergyLabel()
    {
        return $this->container['energy_label'];
    }

    /**
     * Sets energy_label
     *
     * @param string|null $energy_label energy_label
     *
     * @return self
     */
    public function setEnergyLabel($energy_label)
    {
        if (is_null($energy_label)) {
            throw new \InvalidArgumentException('non-nullable energy_label cannot be null');
        }
        $this->container['energy_label'] = $energy_label;

        return $this;
    }

    /**
     * Gets energy_primary_carrier
     *
     * @return string|null
     */
    public function getEnergyPrimaryCarrier()
    {
        return $this->container['energy_primary_carrier'];
    }

    /**
     * Sets energy_primary_carrier
     *
     * @param string|null $energy_primary_carrier energy_primary_carrier
     *
     * @return self
     */
    public function setEnergyPrimaryCarrier($energy_primary_carrier)
    {
        if (is_null($energy_primary_carrier)) {
            throw new \InvalidArgumentException('non-nullable energy_primary_carrier cannot be null');
        }
        $this->container['energy_primary_carrier'] = $energy_primary_carrier;

        return $this;
    }

    /**
     * Gets exterior_features
     *
     * @return string[]|null
     */
    public function getExteriorFeatures()
    {
        return $this->container['exterior_features'];
    }

    /**
     * Sets exterior_features
     *
     * @param string[]|null $exterior_features exterior_features
     *
     * @return self
     */
    public function setExteriorFeatures($exterior_features)
    {
        if (is_null($exterior_features)) {
            throw new \InvalidArgumentException('non-nullable exterior_features cannot be null');
        }
        $this->container['exterior_features'] = $exterior_features;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        if (is_null($external_id)) {
            throw new \InvalidArgumentException('non-nullable external_id cannot be null');
        }
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets floor
     *
     * @return int|null
     */
    public function getFloor()
    {
        return $this->container['floor'];
    }

    /**
     * Sets floor
     *
     * @param int|null $floor floor
     *
     * @return self
     */
    public function setFloor($floor)
    {
        if (is_null($floor)) {
            throw new \InvalidArgumentException('non-nullable floor cannot be null');
        }
        $this->container['floor'] = $floor;

        return $this;
    }

    /**
     * Gets flooring
     *
     * @return string|null
     */
    public function getFlooring()
    {
        return $this->container['flooring'];
    }

    /**
     * Sets flooring
     *
     * @param string|null $flooring flooring
     *
     * @return self
     */
    public function setFlooring($flooring)
    {
        if (is_null($flooring)) {
            throw new \InvalidArgumentException('non-nullable flooring cannot be null');
        }
        $this->container['flooring'] = $flooring;

        return $this;
    }

    /**
     * Gets floors_in_building
     *
     * @return int|null
     */
    public function getFloorsInBuilding()
    {
        return $this->container['floors_in_building'];
    }

    /**
     * Sets floors_in_building
     *
     * @param int|null $floors_in_building floors_in_building
     *
     * @return self
     */
    public function setFloorsInBuilding($floors_in_building)
    {
        if (is_null($floors_in_building)) {
            throw new \InvalidArgumentException('non-nullable floors_in_building cannot be null');
        }
        $this->container['floors_in_building'] = $floors_in_building;

        return $this;
    }

    /**
     * Gets garden_sqm
     *
     * @return float|null
     */
    public function getGardenSqm()
    {
        return $this->container['garden_sqm'];
    }

    /**
     * Sets garden_sqm
     *
     * @param float|null $garden_sqm garden_sqm
     *
     * @return self
     */
    public function setGardenSqm($garden_sqm)
    {
        if (is_null($garden_sqm)) {
            throw new \InvalidArgumentException('non-nullable garden_sqm cannot be null');
        }
        $this->container['garden_sqm'] = $garden_sqm;

        return $this;
    }

    /**
     * Gets half_bathrooms
     *
     * @return int|null
     */
    public function getHalfBathrooms()
    {
        return $this->container['half_bathrooms'];
    }

    /**
     * Sets half_bathrooms
     *
     * @param int|null $half_bathrooms half_bathrooms
     *
     * @return self
     */
    public function setHalfBathrooms($half_bathrooms)
    {
        if (is_null($half_bathrooms)) {
            throw new \InvalidArgumentException('non-nullable half_bathrooms cannot be null');
        }
        $this->container['half_bathrooms'] = $half_bathrooms;

        return $this;
    }

    /**
     * Gets has_air_conditioning
     *
     * @return bool|null
     */
    public function getHasAirConditioning()
    {
        return $this->container['has_air_conditioning'];
    }

    /**
     * Sets has_air_conditioning
     *
     * @param bool|null $has_air_conditioning has_air_conditioning
     *
     * @return self
     */
    public function setHasAirConditioning($has_air_conditioning)
    {
        if (is_null($has_air_conditioning)) {
            throw new \InvalidArgumentException('non-nullable has_air_conditioning cannot be null');
        }
        $this->container['has_air_conditioning'] = $has_air_conditioning;

        return $this;
    }

    /**
     * Gets has_alarm_system
     *
     * @return bool|null
     */
    public function getHasAlarmSystem()
    {
        return $this->container['has_alarm_system'];
    }

    /**
     * Sets has_alarm_system
     *
     * @param bool|null $has_alarm_system has_alarm_system
     *
     * @return self
     */
    public function setHasAlarmSystem($has_alarm_system)
    {
        if (is_null($has_alarm_system)) {
            throw new \InvalidArgumentException('non-nullable has_alarm_system cannot be null');
        }
        $this->container['has_alarm_system'] = $has_alarm_system;

        return $this;
    }

    /**
     * Gets has_balcony
     *
     * @return bool|null
     */
    public function getHasBalcony()
    {
        return $this->container['has_balcony'];
    }

    /**
     * Sets has_balcony
     *
     * @param bool|null $has_balcony has_balcony
     *
     * @return self
     */
    public function setHasBalcony($has_balcony)
    {
        if (is_null($has_balcony)) {
            throw new \InvalidArgumentException('non-nullable has_balcony cannot be null');
        }
        $this->container['has_balcony'] = $has_balcony;

        return $this;
    }

    /**
     * Gets has_cellar
     *
     * @return bool|null
     */
    public function getHasCellar()
    {
        return $this->container['has_cellar'];
    }

    /**
     * Sets has_cellar
     *
     * @param bool|null $has_cellar has_cellar
     *
     * @return self
     */
    public function setHasCellar($has_cellar)
    {
        if (is_null($has_cellar)) {
            throw new \InvalidArgumentException('non-nullable has_cellar cannot be null');
        }
        $this->container['has_cellar'] = $has_cellar;

        return $this;
    }

    /**
     * Gets has_fireplace
     *
     * @return bool|null
     */
    public function getHasFireplace()
    {
        return $this->container['has_fireplace'];
    }

    /**
     * Sets has_fireplace
     *
     * @param bool|null $has_fireplace has_fireplace
     *
     * @return self
     */
    public function setHasFireplace($has_fireplace)
    {
        if (is_null($has_fireplace)) {
            throw new \InvalidArgumentException('non-nullable has_fireplace cannot be null');
        }
        $this->container['has_fireplace'] = $has_fireplace;

        return $this;
    }

    /**
     * Gets has_fitted_kitchen
     *
     * @return bool|null
     */
    public function getHasFittedKitchen()
    {
        return $this->container['has_fitted_kitchen'];
    }

    /**
     * Sets has_fitted_kitchen
     *
     * @param bool|null $has_fitted_kitchen has_fitted_kitchen
     *
     * @return self
     */
    public function setHasFittedKitchen($has_fitted_kitchen)
    {
        if (is_null($has_fitted_kitchen)) {
            throw new \InvalidArgumentException('non-nullable has_fitted_kitchen cannot be null');
        }
        $this->container['has_fitted_kitchen'] = $has_fitted_kitchen;

        return $this;
    }

    /**
     * Gets has_garden
     *
     * @return bool|null
     */
    public function getHasGarden()
    {
        return $this->container['has_garden'];
    }

    /**
     * Sets has_garden
     *
     * @param bool|null $has_garden has_garden
     *
     * @return self
     */
    public function setHasGarden($has_garden)
    {
        if (is_null($has_garden)) {
            throw new \InvalidArgumentException('non-nullable has_garden cannot be null');
        }
        $this->container['has_garden'] = $has_garden;

        return $this;
    }

    /**
     * Gets has_guest_toilet
     *
     * @return bool|null
     */
    public function getHasGuestToilet()
    {
        return $this->container['has_guest_toilet'];
    }

    /**
     * Sets has_guest_toilet
     *
     * @param bool|null $has_guest_toilet has_guest_toilet
     *
     * @return self
     */
    public function setHasGuestToilet($has_guest_toilet)
    {
        if (is_null($has_guest_toilet)) {
            throw new \InvalidArgumentException('non-nullable has_guest_toilet cannot be null');
        }
        $this->container['has_guest_toilet'] = $has_guest_toilet;

        return $this;
    }

    /**
     * Gets has_lift
     *
     * @return bool|null
     */
    public function getHasLift()
    {
        return $this->container['has_lift'];
    }

    /**
     * Sets has_lift
     *
     * @param bool|null $has_lift has_lift
     *
     * @return self
     */
    public function setHasLift($has_lift)
    {
        if (is_null($has_lift)) {
            throw new \InvalidArgumentException('non-nullable has_lift cannot be null');
        }
        $this->container['has_lift'] = $has_lift;

        return $this;
    }

    /**
     * Gets has_pool
     *
     * @return bool|null
     */
    public function getHasPool()
    {
        return $this->container['has_pool'];
    }

    /**
     * Sets has_pool
     *
     * @param bool|null $has_pool has_pool
     *
     * @return self
     */
    public function setHasPool($has_pool)
    {
        if (is_null($has_pool)) {
            throw new \InvalidArgumentException('non-nullable has_pool cannot be null');
        }
        $this->container['has_pool'] = $has_pool;

        return $this;
    }

    /**
     * Gets has_sauna
     *
     * @return bool|null
     */
    public function getHasSauna()
    {
        return $this->container['has_sauna'];
    }

    /**
     * Sets has_sauna
     *
     * @param bool|null $has_sauna has_sauna
     *
     * @return self
     */
    public function setHasSauna($has_sauna)
    {
        if (is_null($has_sauna)) {
            throw new \InvalidArgumentException('non-nullable has_sauna cannot be null');
        }
        $this->container['has_sauna'] = $has_sauna;

        return $this;
    }

    /**
     * Gets has_solar_panels
     *
     * @return bool|null
     */
    public function getHasSolarPanels()
    {
        return $this->container['has_solar_panels'];
    }

    /**
     * Sets has_solar_panels
     *
     * @param bool|null $has_solar_panels has_solar_panels
     *
     * @return self
     */
    public function setHasSolarPanels($has_solar_panels)
    {
        if (is_null($has_solar_panels)) {
            throw new \InvalidArgumentException('non-nullable has_solar_panels cannot be null');
        }
        $this->container['has_solar_panels'] = $has_solar_panels;

        return $this;
    }

    /**
     * Gets has_terrace
     *
     * @return bool|null
     */
    public function getHasTerrace()
    {
        return $this->container['has_terrace'];
    }

    /**
     * Sets has_terrace
     *
     * @param bool|null $has_terrace has_terrace
     *
     * @return self
     */
    public function setHasTerrace($has_terrace)
    {
        if (is_null($has_terrace)) {
            throw new \InvalidArgumentException('non-nullable has_terrace cannot be null');
        }
        $this->container['has_terrace'] = $has_terrace;

        return $this;
    }

    /**
     * Gets heating_type
     *
     * @return string|null
     */
    public function getHeatingType()
    {
        return $this->container['heating_type'];
    }

    /**
     * Sets heating_type
     *
     * @param string|null $heating_type heating_type
     *
     * @return self
     */
    public function setHeatingType($heating_type)
    {
        if (is_null($heating_type)) {
            throw new \InvalidArgumentException('non-nullable heating_type cannot be null');
        }
        $this->container['heating_type'] = $heating_type;

        return $this;
    }

    /**
     * Gets images
     *
     * @return \Skautik\Sdk\Model\ImageInput[]|null
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \Skautik\Sdk\Model\ImageInput[]|null $images images
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            throw new \InvalidArgumentException('non-nullable images cannot be null');
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets interior_features
     *
     * @return string[]|null
     */
    public function getInteriorFeatures()
    {
        return $this->container['interior_features'];
    }

    /**
     * Sets interior_features
     *
     * @param string[]|null $interior_features interior_features
     *
     * @return self
     */
    public function setInteriorFeatures($interior_features)
    {
        if (is_null($interior_features)) {
            throw new \InvalidArgumentException('non-nullable interior_features cannot be null');
        }
        $this->container['interior_features'] = $interior_features;

        return $this;
    }

    /**
     * Gets is_barrier_free
     *
     * @return bool|null
     */
    public function getIsBarrierFree()
    {
        return $this->container['is_barrier_free'];
    }

    /**
     * Sets is_barrier_free
     *
     * @param bool|null $is_barrier_free is_barrier_free
     *
     * @return self
     */
    public function setIsBarrierFree($is_barrier_free)
    {
        if (is_null($is_barrier_free)) {
            throw new \InvalidArgumentException('non-nullable is_barrier_free cannot be null');
        }
        $this->container['is_barrier_free'] = $is_barrier_free;

        return $this;
    }

    /**
     * Gets is_furnished
     *
     * @return bool|null
     */
    public function getIsFurnished()
    {
        return $this->container['is_furnished'];
    }

    /**
     * Sets is_furnished
     *
     * @param bool|null $is_furnished is_furnished
     *
     * @return self
     */
    public function setIsFurnished($is_furnished)
    {
        if (is_null($is_furnished)) {
            throw new \InvalidArgumentException('non-nullable is_furnished cannot be null');
        }
        $this->container['is_furnished'] = $is_furnished;

        return $this;
    }

    /**
     * Gets is_leasehold
     *
     * @return bool|null
     */
    public function getIsLeasehold()
    {
        return $this->container['is_leasehold'];
    }

    /**
     * Sets is_leasehold
     *
     * @param bool|null $is_leasehold is_leasehold
     *
     * @return self
     */
    public function setIsLeasehold($is_leasehold)
    {
        if (is_null($is_leasehold)) {
            throw new \InvalidArgumentException('non-nullable is_leasehold cannot be null');
        }
        $this->container['is_leasehold'] = $is_leasehold;

        return $this;
    }

    /**
     * Gets is_monument_protected
     *
     * @return bool|null
     */
    public function getIsMonumentProtected()
    {
        return $this->container['is_monument_protected'];
    }

    /**
     * Sets is_monument_protected
     *
     * @param bool|null $is_monument_protected is_monument_protected
     *
     * @return self
     */
    public function setIsMonumentProtected($is_monument_protected)
    {
        if (is_null($is_monument_protected)) {
            throw new \InvalidArgumentException('non-nullable is_monument_protected cannot be null');
        }
        $this->container['is_monument_protected'] = $is_monument_protected;

        return $this;
    }

    /**
     * Gets kitchen_type
     *
     * @return string|null
     */
    public function getKitchenType()
    {
        return $this->container['kitchen_type'];
    }

    /**
     * Sets kitchen_type
     *
     * @param string|null $kitchen_type kitchen_type
     *
     * @return self
     */
    public function setKitchenType($kitchen_type)
    {
        if (is_null($kitchen_type)) {
            throw new \InvalidArgumentException('non-nullable kitchen_type cannot be null');
        }
        $this->container['kitchen_type'] = $kitchen_type;

        return $this;
    }

    /**
     * Gets latitude
     *
     * @return float|null
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     *
     * @param float|null $latitude latitude
     *
     * @return self
     */
    public function setLatitude($latitude)
    {
        if (is_null($latitude)) {
            throw new \InvalidArgumentException('non-nullable latitude cannot be null');
        }
        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets listing
     *
     * @return \Skautik\Sdk\Model\ListingInput|null
     */
    public function getListing()
    {
        return $this->container['listing'];
    }

    /**
     * Sets listing
     *
     * @param \Skautik\Sdk\Model\ListingInput|null $listing listing
     *
     * @return self
     */
    public function setListing($listing)
    {
        if (is_null($listing)) {
            throw new \InvalidArgumentException('non-nullable listing cannot be null');
        }
        $this->container['listing'] = $listing;

        return $this;
    }

    /**
     * Gets living_area_sqm
     *
     * @return float|null
     */
    public function getLivingAreaSqm()
    {
        return $this->container['living_area_sqm'];
    }

    /**
     * Sets living_area_sqm
     *
     * @param float|null $living_area_sqm living_area_sqm
     *
     * @return self
     */
    public function setLivingAreaSqm($living_area_sqm)
    {
        if (is_null($living_area_sqm)) {
            throw new \InvalidArgumentException('non-nullable living_area_sqm cannot be null');
        }
        $this->container['living_area_sqm'] = $living_area_sqm;

        return $this;
    }

    /**
     * Gets location_precision
     *
     * @return string|null
     */
    public function getLocationPrecision()
    {
        return $this->container['location_precision'];
    }

    /**
     * Sets location_precision
     *
     * @param string|null $location_precision location_precision
     *
     * @return self
     */
    public function setLocationPrecision($location_precision)
    {
        if (is_null($location_precision)) {
            throw new \InvalidArgumentException('non-nullable location_precision cannot be null');
        }
        $this->container['location_precision'] = $location_precision;

        return $this;
    }

    /**
     * Gets longitude
     *
     * @return float|null
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     *
     * @param float|null $longitude longitude
     *
     * @return self
     */
    public function setLongitude($longitude)
    {
        if (is_null($longitude)) {
            throw new \InvalidArgumentException('non-nullable longitude cannot be null');
        }
        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets office_area_sqm
     *
     * @return float|null
     */
    public function getOfficeAreaSqm()
    {
        return $this->container['office_area_sqm'];
    }

    /**
     * Sets office_area_sqm
     *
     * @param float|null $office_area_sqm office_area_sqm
     *
     * @return self
     */
    public function setOfficeAreaSqm($office_area_sqm)
    {
        if (is_null($office_area_sqm)) {
            throw new \InvalidArgumentException('non-nullable office_area_sqm cannot be null');
        }
        $this->container['office_area_sqm'] = $office_area_sqm;

        return $this;
    }

    /**
     * Gets other_area_sqm
     *
     * @return float|null
     */
    public function getOtherAreaSqm()
    {
        return $this->container['other_area_sqm'];
    }

    /**
     * Sets other_area_sqm
     *
     * @param float|null $other_area_sqm other_area_sqm
     *
     * @return self
     */
    public function setOtherAreaSqm($other_area_sqm)
    {
        if (is_null($other_area_sqm)) {
            throw new \InvalidArgumentException('non-nullable other_area_sqm cannot be null');
        }
        $this->container['other_area_sqm'] = $other_area_sqm;

        return $this;
    }

    /**
     * Gets parking_included
     *
     * @return bool|null
     */
    public function getParkingIncluded()
    {
        return $this->container['parking_included'];
    }

    /**
     * Sets parking_included
     *
     * @param bool|null $parking_included parking_included
     *
     * @return self
     */
    public function setParkingIncluded($parking_included)
    {
        if (is_null($parking_included)) {
            throw new \InvalidArgumentException('non-nullable parking_included cannot be null');
        }
        $this->container['parking_included'] = $parking_included;

        return $this;
    }

    /**
     * Gets parking_space_count
     *
     * @return int|null
     */
    public function getParkingSpaceCount()
    {
        return $this->container['parking_space_count'];
    }

    /**
     * Sets parking_space_count
     *
     * @param int|null $parking_space_count parking_space_count
     *
     * @return self
     */
    public function setParkingSpaceCount($parking_space_count)
    {
        if (is_null($parking_space_count)) {
            throw new \InvalidArgumentException('non-nullable parking_space_count cannot be null');
        }
        $this->container['parking_space_count'] = $parking_space_count;

        return $this;
    }

    /**
     * Gets parking_type
     *
     * @return string|null
     */
    public function getParkingType()
    {
        return $this->container['parking_type'];
    }

    /**
     * Sets parking_type
     *
     * @param string|null $parking_type parking_type
     *
     * @return self
     */
    public function setParkingType($parking_type)
    {
        if (is_null($parking_type)) {
            throw new \InvalidArgumentException('non-nullable parking_type cannot be null');
        }
        $this->container['parking_type'] = $parking_type;

        return $this;
    }

    /**
     * Gets plot_area_sqm
     *
     * @return float|null
     */
    public function getPlotAreaSqm()
    {
        return $this->container['plot_area_sqm'];
    }

    /**
     * Sets plot_area_sqm
     *
     * @param float|null $plot_area_sqm plot_area_sqm
     *
     * @return self
     */
    public function setPlotAreaSqm($plot_area_sqm)
    {
        if (is_null($plot_area_sqm)) {
            throw new \InvalidArgumentException('non-nullable plot_area_sqm cannot be null');
        }
        $this->container['plot_area_sqm'] = $plot_area_sqm;

        return $this;
    }

    /**
     * Gets property_subtype
     *
     * @return string|null
     */
    public function getPropertySubtype()
    {
        return $this->container['property_subtype'];
    }

    /**
     * Sets property_subtype
     *
     * @param string|null $property_subtype property_subtype
     *
     * @return self
     */
    public function setPropertySubtype($property_subtype)
    {
        if (is_null($property_subtype)) {
            throw new \InvalidArgumentException('non-nullable property_subtype cannot be null');
        }
        $this->container['property_subtype'] = $property_subtype;

        return $this;
    }

    /**
     * Gets publish_address
     *
     * @return bool|null
     */
    public function getPublishAddress()
    {
        return $this->container['publish_address'];
    }

    /**
     * Sets publish_address
     *
     * @param bool|null $publish_address publish_address
     *
     * @return self
     */
    public function setPublishAddress($publish_address)
    {
        if (is_null($publish_address)) {
            throw new \InvalidArgumentException('non-nullable publish_address cannot be null');
        }
        $this->container['publish_address'] = $publish_address;

        return $this;
    }

    /**
     * Gets retail_area_sqm
     *
     * @return float|null
     */
    public function getRetailAreaSqm()
    {
        return $this->container['retail_area_sqm'];
    }

    /**
     * Sets retail_area_sqm
     *
     * @param float|null $retail_area_sqm retail_area_sqm
     *
     * @return self
     */
    public function setRetailAreaSqm($retail_area_sqm)
    {
        if (is_null($retail_area_sqm)) {
            throw new \InvalidArgumentException('non-nullable retail_area_sqm cannot be null');
        }
        $this->container['retail_area_sqm'] = $retail_area_sqm;

        return $this;
    }

    /**
     * Gets storage_area_sqm
     *
     * @return float|null
     */
    public function getStorageAreaSqm()
    {
        return $this->container['storage_area_sqm'];
    }

    /**
     * Sets storage_area_sqm
     *
     * @param float|null $storage_area_sqm storage_area_sqm
     *
     * @return self
     */
    public function setStorageAreaSqm($storage_area_sqm)
    {
        if (is_null($storage_area_sqm)) {
            throw new \InvalidArgumentException('non-nullable storage_area_sqm cannot be null');
        }
        $this->container['storage_area_sqm'] = $storage_area_sqm;

        return $this;
    }

    /**
     * Gets surroundings
     *
     * @return string[]|null
     */
    public function getSurroundings()
    {
        return $this->container['surroundings'];
    }

    /**
     * Sets surroundings
     *
     * @param string[]|null $surroundings surroundings
     *
     * @return self
     */
    public function setSurroundings($surroundings)
    {
        if (is_null($surroundings)) {
            throw new \InvalidArgumentException('non-nullable surroundings cannot be null');
        }
        $this->container['surroundings'] = $surroundings;

        return $this;
    }

    /**
     * Gets terrace_count
     *
     * @return int|null
     */
    public function getTerraceCount()
    {
        return $this->container['terrace_count'];
    }

    /**
     * Sets terrace_count
     *
     * @param int|null $terrace_count terrace_count
     *
     * @return self
     */
    public function setTerraceCount($terrace_count)
    {
        if (is_null($terrace_count)) {
            throw new \InvalidArgumentException('non-nullable terrace_count cannot be null');
        }
        $this->container['terrace_count'] = $terrace_count;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets total_area_sqm
     *
     * @return float|null
     */
    public function getTotalAreaSqm()
    {
        return $this->container['total_area_sqm'];
    }

    /**
     * Sets total_area_sqm
     *
     * @param float|null $total_area_sqm total_area_sqm
     *
     * @return self
     */
    public function setTotalAreaSqm($total_area_sqm)
    {
        if (is_null($total_area_sqm)) {
            throw new \InvalidArgumentException('non-nullable total_area_sqm cannot be null');
        }
        $this->container['total_area_sqm'] = $total_area_sqm;

        return $this;
    }

    /**
     * Gets total_rooms
     *
     * @return int|null
     */
    public function getTotalRooms()
    {
        return $this->container['total_rooms'];
    }

    /**
     * Sets total_rooms
     *
     * @param int|null $total_rooms total_rooms
     *
     * @return self
     */
    public function setTotalRooms($total_rooms)
    {
        if (is_null($total_rooms)) {
            throw new \InvalidArgumentException('non-nullable total_rooms cannot be null');
        }
        $this->container['total_rooms'] = $total_rooms;

        return $this;
    }

    /**
     * Gets translations
     *
     * @return \Skautik\Sdk\Model\Translation[]|null
     */
    public function getTranslations()
    {
        return $this->container['translations'];
    }

    /**
     * Sets translations
     *
     * @param \Skautik\Sdk\Model\Translation[]|null $translations translations
     *
     * @return self
     */
    public function setTranslations($translations)
    {
        if (is_null($translations)) {
            throw new \InvalidArgumentException('non-nullable translations cannot be null');
        }
        $this->container['translations'] = $translations;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets usable_area_sqm
     *
     * @return float|null
     */
    public function getUsableAreaSqm()
    {
        return $this->container['usable_area_sqm'];
    }

    /**
     * Sets usable_area_sqm
     *
     * @param float|null $usable_area_sqm usable_area_sqm
     *
     * @return self
     */
    public function setUsableAreaSqm($usable_area_sqm)
    {
        if (is_null($usable_area_sqm)) {
            throw new \InvalidArgumentException('non-nullable usable_area_sqm cannot be null');
        }
        $this->container['usable_area_sqm'] = $usable_area_sqm;

        return $this;
    }

    /**
     * Gets window_glazing
     *
     * @return string|null
     */
    public function getWindowGlazing()
    {
        return $this->container['window_glazing'];
    }

    /**
     * Sets window_glazing
     *
     * @param string|null $window_glazing window_glazing
     *
     * @return self
     */
    public function setWindowGlazing($window_glazing)
    {
        if (is_null($window_glazing)) {
            throw new \InvalidArgumentException('non-nullable window_glazing cannot be null');
        }
        $this->container['window_glazing'] = $window_glazing;

        return $this;
    }

    /**
     * Gets year_built
     *
     * @return int|null
     */
    public function getYearBuilt()
    {
        return $this->container['year_built'];
    }

    /**
     * Sets year_built
     *
     * @param int|null $year_built year_built
     *
     * @return self
     */
    public function setYearBuilt($year_built)
    {
        if (is_null($year_built)) {
            throw new \InvalidArgumentException('non-nullable year_built cannot be null');
        }
        $this->container['year_built'] = $year_built;

        return $this;
    }

    /**
     * Gets year_renovated
     *
     * @return int|null
     */
    public function getYearRenovated()
    {
        return $this->container['year_renovated'];
    }

    /**
     * Sets year_renovated
     *
     * @param int|null $year_renovated year_renovated
     *
     * @return self
     */
    public function setYearRenovated($year_renovated)
    {
        if (is_null($year_renovated)) {
            throw new \InvalidArgumentException('non-nullable year_renovated cannot be null');
        }
        $this->container['year_renovated'] = $year_renovated;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


