<?php
/**
 * Property
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Skautik\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skautik Partner API
 *
 * The Skautik partner API.  Every endpoint is authenticated by an API key and gated on a per-resource scope, so a key issued for market analysis cannot read anyone's enquiries and a read-only key cannot withdraw a listing.  Responses are enveloped: the payload is under `data`, and anything about the response rather than the resource is under `meta`. Failures are RFC 9457 problem documents carrying a stable `code` to branch on.  Writes accept an `Idempotency-Key`, and replaying one returns the original response rather than repeating the work.  This document is generated from the API's own route tree, so an endpoint that appears here exists and one that exists appears here.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Skautik\Sdk\Model;

use \ArrayAccess;
use \Skautik\Sdk\ObjectSerializer;

/**
 * Property Class Doc Comment
 *
 * @category Class
 * @package  Skautik\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Property implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Property';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'address' => '\Skautik\Sdk\Model\Address',
        'building' => '\Skautik\Sdk\Model\Building',
        'created_at' => '\DateTime',
        'description' => 'string',
        'descriptions' => '\Skautik\Sdk\Model\Descriptions',
        'energy' => '\Skautik\Sdk\Model\Energy',
        'external_id' => 'string',
        'features' => '\Skautik\Sdk\Model\Features',
        'id' => 'string',
        'images' => '\Skautik\Sdk\Model\Image[]',
        'language' => 'string',
        'last_verified_at' => '\DateTime',
        'listing' => '\Skautik\Sdk\Model\Listing',
        'location' => '\Skautik\Sdk\Model\Location',
        'market' => '\Skautik\Sdk\Model\MarketContext',
        'parking' => '\Skautik\Sdk\Model\Parking',
        'price_history' => '\Skautik\Sdk\Model\PriceObservation[]',
        'rooms' => '\Skautik\Sdk\Model\Rooms',
        'size' => '\Skautik\Sdk\Model\Size',
        'source' => 'string',
        'subtype' => 'string',
        'title' => 'string',
        'translations' => '\Skautik\Sdk\Model\Translation[]',
        'type' => 'string',
        'updated_at' => '\DateTime'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'address' => null,
        'building' => null,
        'created_at' => 'date-time',
        'description' => null,
        'descriptions' => null,
        'energy' => null,
        'external_id' => null,
        'features' => null,
        'id' => null,
        'images' => null,
        'language' => null,
        'last_verified_at' => 'date-time',
        'listing' => null,
        'location' => null,
        'market' => null,
        'parking' => null,
        'price_history' => null,
        'rooms' => null,
        'size' => null,
        'source' => null,
        'subtype' => null,
        'title' => null,
        'translations' => null,
        'type' => null,
        'updated_at' => 'date-time'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'address' => false,
        'building' => false,
        'created_at' => false,
        'description' => false,
        'descriptions' => false,
        'energy' => false,
        'external_id' => false,
        'features' => false,
        'id' => false,
        'images' => false,
        'language' => false,
        'last_verified_at' => false,
        'listing' => false,
        'location' => false,
        'market' => false,
        'parking' => false,
        'price_history' => false,
        'rooms' => false,
        'size' => false,
        'source' => false,
        'subtype' => false,
        'title' => false,
        'translations' => false,
        'type' => false,
        'updated_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address' => 'address',
        'building' => 'building',
        'created_at' => 'created_at',
        'description' => 'description',
        'descriptions' => 'descriptions',
        'energy' => 'energy',
        'external_id' => 'external_id',
        'features' => 'features',
        'id' => 'id',
        'images' => 'images',
        'language' => 'language',
        'last_verified_at' => 'last_verified_at',
        'listing' => 'listing',
        'location' => 'location',
        'market' => 'market',
        'parking' => 'parking',
        'price_history' => 'price_history',
        'rooms' => 'rooms',
        'size' => 'size',
        'source' => 'source',
        'subtype' => 'subtype',
        'title' => 'title',
        'translations' => 'translations',
        'type' => 'type',
        'updated_at' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'address' => 'setAddress',
        'building' => 'setBuilding',
        'created_at' => 'setCreatedAt',
        'description' => 'setDescription',
        'descriptions' => 'setDescriptions',
        'energy' => 'setEnergy',
        'external_id' => 'setExternalId',
        'features' => 'setFeatures',
        'id' => 'setId',
        'images' => 'setImages',
        'language' => 'setLanguage',
        'last_verified_at' => 'setLastVerifiedAt',
        'listing' => 'setListing',
        'location' => 'setLocation',
        'market' => 'setMarket',
        'parking' => 'setParking',
        'price_history' => 'setPriceHistory',
        'rooms' => 'setRooms',
        'size' => 'setSize',
        'source' => 'setSource',
        'subtype' => 'setSubtype',
        'title' => 'setTitle',
        'translations' => 'setTranslations',
        'type' => 'setType',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'address' => 'getAddress',
        'building' => 'getBuilding',
        'created_at' => 'getCreatedAt',
        'description' => 'getDescription',
        'descriptions' => 'getDescriptions',
        'energy' => 'getEnergy',
        'external_id' => 'getExternalId',
        'features' => 'getFeatures',
        'id' => 'getId',
        'images' => 'getImages',
        'language' => 'getLanguage',
        'last_verified_at' => 'getLastVerifiedAt',
        'listing' => 'getListing',
        'location' => 'getLocation',
        'market' => 'getMarket',
        'parking' => 'getParking',
        'price_history' => 'getPriceHistory',
        'rooms' => 'getRooms',
        'size' => 'getSize',
        'source' => 'getSource',
        'subtype' => 'getSubtype',
        'title' => 'getTitle',
        'translations' => 'getTranslations',
        'type' => 'getType',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('building', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('descriptions', $data ?? [], null);
        $this->setIfExists('energy', $data ?? [], null);
        $this->setIfExists('external_id', $data ?? [], null);
        $this->setIfExists('features', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('last_verified_at', $data ?? [], null);
        $this->setIfExists('listing', $data ?? [], null);
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('market', $data ?? [], null);
        $this->setIfExists('parking', $data ?? [], null);
        $this->setIfExists('price_history', $data ?? [], null);
        $this->setIfExists('rooms', $data ?? [], null);
        $this->setIfExists('size', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('subtype', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('translations', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['address'] === null) {
            $invalidProperties[] = "'address' can't be null";
        }
        if ($this->container['building'] === null) {
            $invalidProperties[] = "'building' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['rooms'] === null) {
            $invalidProperties[] = "'rooms' can't be null";
        }
        if ($this->container['size'] === null) {
            $invalidProperties[] = "'size' can't be null";
        }
        if ($this->container['source'] === null) {
            $invalidProperties[] = "'source' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address
     *
     * @return \Skautik\Sdk\Model\Address
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \Skautik\Sdk\Model\Address $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets building
     *
     * @return \Skautik\Sdk\Model\Building
     */
    public function getBuilding()
    {
        return $this->container['building'];
    }

    /**
     * Sets building
     *
     * @param \Skautik\Sdk\Model\Building $building building
     *
     * @return self
     */
    public function setBuilding($building)
    {
        if (is_null($building)) {
            throw new \InvalidArgumentException('non-nullable building cannot be null');
        }
        $this->container['building'] = $building;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets descriptions
     *
     * @return \Skautik\Sdk\Model\Descriptions|null
     */
    public function getDescriptions()
    {
        return $this->container['descriptions'];
    }

    /**
     * Sets descriptions
     *
     * @param \Skautik\Sdk\Model\Descriptions|null $descriptions descriptions
     *
     * @return self
     */
    public function setDescriptions($descriptions)
    {
        if (is_null($descriptions)) {
            throw new \InvalidArgumentException('non-nullable descriptions cannot be null');
        }
        $this->container['descriptions'] = $descriptions;

        return $this;
    }

    /**
     * Gets energy
     *
     * @return \Skautik\Sdk\Model\Energy|null
     */
    public function getEnergy()
    {
        return $this->container['energy'];
    }

    /**
     * Sets energy
     *
     * @param \Skautik\Sdk\Model\Energy|null $energy energy
     *
     * @return self
     */
    public function setEnergy($energy)
    {
        if (is_null($energy)) {
            throw new \InvalidArgumentException('non-nullable energy cannot be null');
        }
        $this->container['energy'] = $energy;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        if (is_null($external_id)) {
            throw new \InvalidArgumentException('non-nullable external_id cannot be null');
        }
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets features
     *
     * @return \Skautik\Sdk\Model\Features|null
     */
    public function getFeatures()
    {
        return $this->container['features'];
    }

    /**
     * Sets features
     *
     * @param \Skautik\Sdk\Model\Features|null $features features
     *
     * @return self
     */
    public function setFeatures($features)
    {
        if (is_null($features)) {
            throw new \InvalidArgumentException('non-nullable features cannot be null');
        }
        $this->container['features'] = $features;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets images
     *
     * @return \Skautik\Sdk\Model\Image[]|null
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \Skautik\Sdk\Model\Image[]|null $images images
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            throw new \InvalidArgumentException('non-nullable images cannot be null');
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets last_verified_at
     *
     * @return \DateTime|null
     */
    public function getLastVerifiedAt()
    {
        return $this->container['last_verified_at'];
    }

    /**
     * Sets last_verified_at
     *
     * @param \DateTime|null $last_verified_at last_verified_at
     *
     * @return self
     */
    public function setLastVerifiedAt($last_verified_at)
    {
        if (is_null($last_verified_at)) {
            throw new \InvalidArgumentException('non-nullable last_verified_at cannot be null');
        }
        $this->container['last_verified_at'] = $last_verified_at;

        return $this;
    }

    /**
     * Gets listing
     *
     * @return \Skautik\Sdk\Model\Listing|null
     */
    public function getListing()
    {
        return $this->container['listing'];
    }

    /**
     * Sets listing
     *
     * @param \Skautik\Sdk\Model\Listing|null $listing listing
     *
     * @return self
     */
    public function setListing($listing)
    {
        if (is_null($listing)) {
            throw new \InvalidArgumentException('non-nullable listing cannot be null');
        }
        $this->container['listing'] = $listing;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \Skautik\Sdk\Model\Location|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \Skautik\Sdk\Model\Location|null $location location
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            throw new \InvalidArgumentException('non-nullable location cannot be null');
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets market
     *
     * @return \Skautik\Sdk\Model\MarketContext|null
     */
    public function getMarket()
    {
        return $this->container['market'];
    }

    /**
     * Sets market
     *
     * @param \Skautik\Sdk\Model\MarketContext|null $market market
     *
     * @return self
     */
    public function setMarket($market)
    {
        if (is_null($market)) {
            throw new \InvalidArgumentException('non-nullable market cannot be null');
        }
        $this->container['market'] = $market;

        return $this;
    }

    /**
     * Gets parking
     *
     * @return \Skautik\Sdk\Model\Parking|null
     */
    public function getParking()
    {
        return $this->container['parking'];
    }

    /**
     * Sets parking
     *
     * @param \Skautik\Sdk\Model\Parking|null $parking parking
     *
     * @return self
     */
    public function setParking($parking)
    {
        if (is_null($parking)) {
            throw new \InvalidArgumentException('non-nullable parking cannot be null');
        }
        $this->container['parking'] = $parking;

        return $this;
    }

    /**
     * Gets price_history
     *
     * @return \Skautik\Sdk\Model\PriceObservation[]|null
     */
    public function getPriceHistory()
    {
        return $this->container['price_history'];
    }

    /**
     * Sets price_history
     *
     * @param \Skautik\Sdk\Model\PriceObservation[]|null $price_history price_history
     *
     * @return self
     */
    public function setPriceHistory($price_history)
    {
        if (is_null($price_history)) {
            throw new \InvalidArgumentException('non-nullable price_history cannot be null');
        }
        $this->container['price_history'] = $price_history;

        return $this;
    }

    /**
     * Gets rooms
     *
     * @return \Skautik\Sdk\Model\Rooms
     */
    public function getRooms()
    {
        return $this->container['rooms'];
    }

    /**
     * Sets rooms
     *
     * @param \Skautik\Sdk\Model\Rooms $rooms rooms
     *
     * @return self
     */
    public function setRooms($rooms)
    {
        if (is_null($rooms)) {
            throw new \InvalidArgumentException('non-nullable rooms cannot be null');
        }
        $this->container['rooms'] = $rooms;

        return $this;
    }

    /**
     * Gets size
     *
     * @return \Skautik\Sdk\Model\Size
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param \Skautik\Sdk\Model\Size $size size
     *
     * @return self
     */
    public function setSize($size)
    {
        if (is_null($size)) {
            throw new \InvalidArgumentException('non-nullable size cannot be null');
        }
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string $source source
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets subtype
     *
     * @return string|null
     */
    public function getSubtype()
    {
        return $this->container['subtype'];
    }

    /**
     * Sets subtype
     *
     * @param string|null $subtype subtype
     *
     * @return self
     */
    public function setSubtype($subtype)
    {
        if (is_null($subtype)) {
            throw new \InvalidArgumentException('non-nullable subtype cannot be null');
        }
        $this->container['subtype'] = $subtype;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets translations
     *
     * @return \Skautik\Sdk\Model\Translation[]|null
     */
    public function getTranslations()
    {
        return $this->container['translations'];
    }

    /**
     * Sets translations
     *
     * @param \Skautik\Sdk\Model\Translation[]|null $translations translations
     *
     * @return self
     */
    public function setTranslations($translations)
    {
        if (is_null($translations)) {
            throw new \InvalidArgumentException('non-nullable translations cannot be null');
        }
        $this->container['translations'] = $translations;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


